### ISSUE TITLE
me.sap.com missing in v1.11.0

### ISSUE THREAD

**Issue by mbtools** [dellagustin/SAP_Note_Enhancer#28] opened 2024-08-08 16:48 UTC
Ref #27 

I tried to remove and add again but me.sap.com is not included. Therefore, the highlighting doesn't work anymore:

![image](https://github.com/user-attachments/assets/2c0f066d-859f-44f8-803e-89e49793a49f)

![image](https://github.com/user-attachments/assets/600f0e9a-b603-4ad9-af0c-7ded8f23b310)

**Comment by dellagustin** [comment] 2024-08-08 21:17
It seems we have an intermittent behavior. I'll have to run some tests myself.
If I remember well, the reason I expected it to work on me.sap.com is that the correction instructions are actually shown inside an iframe, and the iframe showed content from a domain that that matches one of the patterns shown in one of the screenhots.
Thank you for reporting.

**Comment by gepparta** [comment] 2024-08-23 06:01
I have the same problem. Would be nice to configure which sites could be accessed by myself in extension properties, for example.

**Comment by dellagustin-sap** [comment] 2024-08-27 07:23
Hi all, I did some debugging, so, it happens that there are different way in which Correction Instructions are shown at me.sap.com, e.g.,:
* https://me.sap.com/corrins/0003171185/15841
* https://me.sap.com/correctioninstruction/0003152012/41/corrinsdetail/0001116049/41/0020751258/0001/756/756/SAP_BASIS/Code

I don't know exactly when one is used or when another is used, but inspecting the pages, the `https://me.sap.com/corrins/ `variant is actually showing the CIs from an iframe that's loading `https://launchpad.support.sap.com//#/corrins/0003171185/15841`

<img width="1655" alt="image" src="https://github.com/user-attachments/assets/0d69412b-c842-495d-8192-8a007d2cce5d">

That's why the extension works, as scripts are injected in that page.

With `https://me.sap.com/correctioninstruction`, I don't see any iframes in place, so I need to update the manifest and test if any of the existing scripts would work.

> Would be nice to configure which sites could be accessed by myself in extension properties, for example.

That's not as simple as it sounds, different pages show CIs in different ways and may require hand crafted javascript code to do the color highlighting.

**Comment by dellagustin-sap** [comment] 2024-08-27 07:51
Good news, extending the launchpad script to `me.sap.com` already produced good results:
<img width="1337" alt="image" src="https://github.com/user-attachments/assets/8818832b-4071-4356-8d94-d182a3cddc2b">

I need to do some more testing, but I should put out a new version soon.

A side question, how often do you get an error like this?
<img width="517" alt="image" src="https://github.com/user-attachments/assets/6092cf24-679c-4288-86a6-3813139db77f">

for me it is quite frequent and it seems to be caused by a 502 Bad Gateway error on different requests.

**Comment by dellagustin-sap** [comment] 2024-08-27 08:02
Ok, so, good news, it works... on microsoft edge.
It did not work on chrome, and then I discovered this: https://developer.chrome.com/blog/mutation-events-deprecation
SAP Note Enhancer observes `DOMNodeInserted` to do the highlighting of the CI code on the launchpad and now on `me.sap.com`, so I need to check how to replace that and retest.

**Comment by dellagustin-sap** [comment] 2024-08-27 12:16
@mbtools @gepparta , the support for me.sap.com is implemented and I additionally fixed a but that was preventing code highlighting in newer versions of chrome.
I sent the new version (1.12.0) for review on the Chrome Web Store, it should be published soon. The review takes from hours to days. I'll leave this issue open until then.

**Comment by mbtools** [comment] 2024-08-27 13:57
Great. It works well with Chrome 128. I got the 502 once but not again. Apps often don't like if you open URLs directly which are so deep into the system. Anyway, thanks for the update 👍

**Comment by dellagustin-sap** [comment] 2024-08-27 14:02
@mbtools @gepparta, version 1.12.0 is out, could you please update and retest?
Chrome will eventually update it, but if you want to update it ahead of time, you can activate the developer tools:
<img width="1669" alt="image" src="https://github.com/user-attachments/assets/805e7023-eb27-4fa0-8791-07ef15c5d226">

I'll close this issue, but we can reopen it if there is any remaining issue.

**Closed as completed by dellagustin-sap** 2024-08-27 14:02 UTC
Labels: bug, enhancement

**Comment by gepparta** [comment] 2024-08-27 15:31
Works on my machine
